### ISSUE TITLE
Add 'I know this nominee personally' checkbox to nomination form

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#23]
Also do this for Justice Democrats.

**Comment by chadwickmeyer** [comment]
I added the field to the form, but it's not pushed to the production server, because the API doesn't support it yet. I spent all day Friday learning how to make update the API and add fields to the OpenTable and NationBuilder databases, but my tests were not successful. The record gets added but the new property doesn't get populated. There is likely a problem with my code in the API. I've pushed my code to my repository (https://github.com/chadwickmeyer/BNC-API) for review. I need @saikat or someone else who knows the API to help. Once I do this once, I'll be able to make these sorts of changes in the future.

**Comment by chadwickmeyer** [comment]
@saikat has this field been added to the API yet? I pushed my changes to my fork of the API repo 2 weeks ago, but I wasn't able to successfully get the API to process the field.

**Comment by saikat** [comment]
No it hasn't yet.  Will try to get to this soon.

**Comment by chadwickmeyer** [comment]
Is this something @ben-pr-p can do?

**Comment by chadwickmeyer** [comment]
@ben-pr-p can you add this single field to the API? I've got work on this that I completed a month and a half ago that I haven't been able to push because the API just needs this single field.

**Comment by ben-pr-p** [comment]
Yeah, sorry - on it

**Comment by chadwickmeyer** [comment]
Three cheers for @ben-pr-p for saving the day. This has been completed and pushed to production. The "I know this nominee personally" checkbox is now on the nominate forms.
