### ISSUE TITLE
Add current team leaders + staff to /about

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#8]

**Comment by chadwickmeyer** [comment]
@saikat Please provide a list of team leaders and staff, as well as bios and high res images. Or provide me the contact information for who can acquire this information.

**Comment by danielameyer** [comment]
Should we be asking Corbin for some of this information?

**Comment by chadwickmeyer** [comment]
I don't know Corbin, so perhaps @danielameyer you could do this. @saikat is just too busy to be managing this stuff anymore, so we need to take ownership of it.

**Comment by danielameyer** [comment]
I let Corbin know, I'll make sure it happens.

**Comment by saikat** [comment]
Can we read this stuff directly from https://airtable.com/shrTfLXBIfpYTZVOD.  Airtable has an API, which @ben-pr-p can possibly hook up to via hub.

**Comment by saikat** [comment]
We just need to make all the team leads add a photo in airtable + a profile.  We could ask Haley to get them to do that.

**Comment by ben-pr-p** [comment]
Sure, though it probably is overkill / a bad idea to have the team loaded with AJAX for the site. Much easier to just export those selected rows from Airtable each time we want to update it. @chadwickmeyer, any format that's best?

**Comment by chadwickmeyer** [comment]
I would prefer adding the team profiles to the website CMS just like other content on the site.

I understand that this may seem like a little bit redundant work to have the data in multiple places, but its much easier to just let our existing profiles list and details pages display the data locally, rather than trying to create a custom page and design to pull the data from airtable via an API. It also keeps all the content on the website editable from the website CMS Admin (and soon live edit). So administration becomes much simpler in the long run. Otherwise the website becomes a Frankenstein where people don't know how or where to edit stuff.

**Comment by chadwickmeyer** [comment]
If you tell me where to get the bios and photos (as high quality and professional looking as possible please), I'll create the pages.

**Comment by saikat** [comment]
https://airtable.com/shrTfLXBIfpYTZVOD is our list of team leads.  Not
everyone has a profile or image though, so we need to ask Haley to collect
those.  I just asked her.
